### ISSUE TITLE
Usage example should use v1.8.0 instead

### ISSUE THREAD

**Issue by hibearpanda** [LanceMcCarthy/Action-AzureBlobUpload#104]
Hello, thank you for creating this action.

I noticed that I had to use `v1.8.0` instead of `v1.8` as the release and example indicates, otherwise the Github Action runner will fail:

<img width="1122" alt="Screenshot 2021-01-12 at 10 27 11 AM" src="https://user-images.githubusercontent.com/11482515/104261557-c3c73b00-54c0-11eb-892b-9aabeb5fface.png">

**Comment by LanceMcCarthy** [comment]
Thanks for taking the time to open this issue so I can fix it for everyone else.
