### ISSUE TITLE
Uploaded file is missing

### ISSUE THREAD

**Issue by hibearpanda** [LanceMcCarthy/Action-AzureBlobUpload#113]
Hello, thank you for writing this github action - it was incredibly useful.

We've been using this package to upload the results (3 files) of an application build to a specific Azure container for distribution.

We've noticed that at times only 2 of the 3 files are uploaded - this occurs randomly. The action will print that all 3 have been uploaded, but when I check the Azure Container, only 2 files remain.

This is a screenshot of the github action output and our current configuration:
<img width="1307" alt="Screenshot 2021-03-17 at 9 16 43 AM" src="https://user-images.githubusercontent.com/11482515/111400561-85d5d580-8702-11eb-8f10-86b45daea753.png">

I am wondering if this is related to the [`clean_destination_folder` setting](https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/253b5255795905c2e6f137b276aa2afb1adda2d8/src/methods-azure.ts#L34).
Specifically, do we need to `await` on [line 38](https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/253b5255795905c2e6f137b276aa2afb1adda2d8/src/methods-azure.ts#L38) when we call `delete`?

Here is what I think is happening:
1. Program calls `delete` but does not wait for the result.
2. After `delete`calls, proceeds to the uploading part
3. A race condition occurs because uploads will overwrite ([at least it looks it will](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/blockblobclient?view=azure-node-latest), and at times, the first file is uploaded before the blob delete is completed via garbage collection.
![Screenshot 2021-03-17 at 9 36 14 AM](https://user-images.githubusercontent.com/11482515/111401602-8bccb600-8704-11eb-870b-4ccfa19c1c43.png)
![Screenshot 2021-03-17 at 9 39 00 AM](https://user-images.githubusercontent.com/11482515/111401650-a56dfd80-8704-11eb-9891-aa9b718394ee.png)

My suggestion is we should try `await`ing the `delete` call, and see if this solves the issue.

Please let me know if you would like me to submit a PR. Would be glad to help.

**Comment by LanceMcCarthy** [comment]
Hi! I'm more than happy to accept PRs.

I won't be able to investigate this until tomorrow, so what ever additional info you can provide or a PR that helps, I'll review and merge it asap

**Comment by LanceMcCarthy** [comment]
The API apparently treats blobs differently if there are any snapshots:

![image](https://user-images.githubusercontent.com/3520532/111481010-ee27b580-8708-11eb-94e7-63be9611cf2f.png)


Looking at the API reference for delete it shows that I can pass in a `BlobDeleteOptions` parameter:

https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-storage-blob/12.0.1/classes/blockblobclient.html#delete

In order to resolve this, it seems I might need to set BlobDeleteOptions with deleteSnaphots = true.

https://azuresdkdocs.blob.core.windows.net/$web/javascript/azure-storage-blob/12.0.1/interfaces/blobdeleteoptions.html

**Comment by LanceMcCarthy** [comment]
v1.8.2 is live, let me know if you have any further issues.

**Comment by hibearpanda** [comment]
Thank you Lance!
