### ISSUE TITLE
Using 1.6, now I am losing the last character of the filename

### ISSUE THREAD

**Issue by jdenicola-pa** [LanceMcCarthy/Action-AzureBlobUpload#23]
Thanks for looking at the previous issue with it losing the first character of the filename... but now it's losing the last character.

My action:

    env:
        AZURE_WEBAPP_PACKAGE_PATH: '.' 

    - name: Copy test data to blob storage container        
      uses: LanceMcCarthy/Action-AzureBlobUpload@v1.6
      with:
        connection_string: XXX
        container_name: dataloader
        source_folder: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/TestData'
        destination_folder: sample
        clean_destination_folder: true

I have a file under the TestData folder named "Xx-Yyy-Z Data.xlsx"

It uploads to the container, but the name is "Xx-Yyy-Z Data.xls" - missing the final "x".

**Comment by LanceMcCarthy** [comment]
Thanks, it is happening to all the files :/ This appears to be a regression I added in a rush to get the empty folder issue fixed.

**Comment by LanceMcCarthy** [comment]
okay, I found the issue and fixed it in v1.7 (rolling out momentarily).

I confirmed the following results after the fix:

## No Destination Folder Test

* Yellow highlight is only file uploaded, no target

![image](https://user-images.githubusercontent.com/3520532/91893420-1581ce00-ec62-11ea-869b-589b0ce1adeb.png)

> Ignore `MyTargetFolder` for now, that is result from the next test.

## Destination Folder Test

* Yellow highlight is destination folder
* green highlight is content 

![image](https://user-images.githubusercontent.com/3520532/91894790-36e3b980-ec64-11ea-845e-fb6bb0aa2253.png)


![image](https://user-images.githubusercontent.com/3520532/91894782-34815f80-ec64-11ea-94ce-c88f6e1f6c3e.png)
