### ISSUE TITLE
Action is renaming uploaded files, not preserving original name

### ISSUE THREAD

**Issue by andrewconnell** [LanceMcCarthy/Action-AzureBlobUpload#34]
I have two files in a folder to upload to the root of an existing container (no sync, no cleaning). I can't figure out looking at the code why this action is renaming my files. Here's the debug output (masking some names with `$` because these are customer product downloads).

As you can see from the following logs, it's replacing my filenames with timestamps (YYYYMMDD) and appending `als` to one of them. I can't see in your code where you're using a datestamp, so I'm assuming that's coming from my filename... it's almost like it's having issues with the underscore in my filename... but why?

```
##[debug]..=> '/home/runner/work/course-$$$$/course-$$$$'
##[debug]=> '/home/runner/work/course-$$$$/course-$$$$/../azblobupload'
##[debug]Result: '/home/runner/work/course-$$$$/course-$$$$/../azblobupload'
##[debug]Loading env
Run LanceMcCarthy/Action-AzureBlobUpload@v1.7
  with:
    connection_string: ***
    container_name: downloads
    source_folder: /home/runner/work/course-$$$$/course-$$$$/../azblobupload
    clean_destination_folder: false
    fail_if_source_empty: false
  env:
    UTILITY_RELATIVE_PATH: utils/build-materials-download
    CURRENT_DATESTAMP: 20200913
##[debug]sourceFolder: /home/runner/work/course-$$$$/course-$$$$/../azblobupload
##[debug]--- cleaned: /home/runner/work/course-$$$$/course-$$$$/../azblobupload
##[debug]localFilePath: /home/runner/work/course-$$$$/azblobupload/$$$$-$$$1_20200913.zip
##[debug]--- cleaned: /home/runner/work/course-$$$$/azblobupload/$$$$-$$$1_20200913.zip
##[debug]finalPath: als_20200913.zip...
##[debug]sourceFolder: /home/runner/work/course-$$$$/course-$$$$/../azblobupload
##[debug]--- cleaned: /home/runner/work/course-$$$$/course-$$$$/../azblobupload
##[debug]localFilePath: /home/runner/work/course-$$$$/azblobupload/$$$$-$$$2_20200913.zip
##[debug]--- cleaned: /home/runner/work/course-$$$$/azblobupload/$$$$-$$$2_20200913.zip
##[debug]finalPath: 20200913.zip...
Uploaded /home/runner/work/course-$$$$/azblobupload/$$$$-$$$1_20200913.zip to downloads/als_20200913.zip...
Uploaded /home/runner/work/course-$$$$/azblobupload/$$$$-$$$2_20200913.zip to downloads/20200913.zip...
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Upload ZIPs to Azure Storage Blob
```

**Comment by LanceMcCarthy** [comment]
Thank you for sharing. This is indeed weird as there is nothing that explicitly changes the name of the file, the only path modifications are stripping off the source root and prefixing any destination root.

I'll take a look at this today, what runner are you using?

**Comment by andrewconnell** [comment]
Latest Ubuntu

**Comment by LanceMcCarthy** [comment]
If you need to be up and running now, try the Docker-based Azure Blob upload action from Matthew Fisher https://github.com/marketplace/actions/azure-blob-storage-upload. The parameters are every similar to mine because the Azure SDK is the same for everyone.


In the meantime, I'll continue to test this.

Regarding the timestamp filename, that value seems to be coming from the environment variable ` CURRENT_DATESTAMP` in the workflow. I don't use that variable in the Action, so I have no idea how that could possible become the filename.

However, I do have an ideas about where the 'als' part is coming from. Do you have a previous folder name that ends in `als`? For example, here's something I think make sense in the context

azblobupload/fin**als**/filename.zip

The ../ in the source path is breaking the file path creation here https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/8ce3f6e52c72185c3a1b70098193ab97384d6188/src/main.ts#L61-L106

**Comment by andrewconnell** [comment]
I'm uploading the files as artifacts so my short term solution is to manually download & upload the files. Not ideal, but the workflow is only manually run so not a big issue.

The timestamp is part of the filename I'm passing into the action. The **als** may be coming from the word "fundament**als**" which is one of the two things I'm masking in the OP of this issue... but there's another word used that didn't generate that... which is strange.

The reason for the ".."in the filename is because of the variable `${{ github.workspace }}` points to the cloned repo in the workspace. The location where the ZIP files are that I want to upload is parallel to that folder. If there was a way to get the value of the folder path for the root of the repo (and not the identical folder name one level down), I could use that... but can't figure how to get around that.

**Comment by LanceMcCarthy** [comment]
The workspace is typically one level down from where the commands are run.  So you _should_ be able to just use:

`source_folder: ..\azblobupload`

Let me know how that goes.

**Comment by LanceMcCarthy** [comment]
Also, I have [This Prebuilt TypeScript Playground](https://www.typescriptlang.org/play?#code/PTAEFEDkBVwJVATQPIFUHgBoAVwGFYARUbAQWgAkBlUC+cAKAGMB7AOwGcAXUDlgVwBOTAKYAxFgBsAJiMGgAvKABEHYcGgjuhAIZcdGkQA8uYgJaSRm7nBYsuwZQ0s9JLJjsnnL2PQAtFFTUmQ209A00TbystLlt7YD8RSTcAOi4TJxdQWW4zNj0zdgkZOUDlJwYGEFBSJi4itgBaUgAvIREAITcAI1QABzcdaVA3AHMzJlAAdwtJUEF+NgAaXhERUAAZFjGOUHzQLiSFszG-Hn6dNhFmdm5QJksrkWkqAWFxKVlBXyPAviEohK31SghEgx0ogAFMAADqw4BjVYAcmAyIAlABuW6cHiPETPaTRX4BJRuDxeCwiEmg8GSSEiGHwxEotFY5wiPFPa7SQixfKFYpfMpKZHI7E4viWVLjKEAAwBH2BcgAXKAACQAb0VQOFggAvnL2axOFIRDKdvKmtaHtyXmqtfjCW9AZ9Sj9-Ib2ZKzRaxvLyZ5if4HZrA5SfJ6jdiTVLzbK5damraCTzQ06ecGjl6JWYAGagKG5BoFBpC92gACEClFGNAmoYoFANTgdIZoDzLEE0x0ghGHHpHCSe1mfx6kIA1j2+7xB8PGynCXy8qXGsr5EpiwKy2x17SIdC4QikaBURiJU2WyIALYsABuGye0nyY1AVxGT5fs50Q60C4zLzLiWgq7nqgQAby-KruW3wLk2qQcIMZhcFCZ7onBoCpHmFhcHIUJGIoAB8oBGOhTbwQAViw+SoWyF4PHcvoJlu0Gge6oYsSB645v+jHSgmNoQemdqQSuXF6jx+pVNUYB8rhgjXvkX5HBsYL0g0D6gJcY4AJ6HIIZjXopbCvipvDvKIWn+B2ggsNehzHHmtlsDwLAFmZ3AGSZqSSjwXAGdeVD6IIXDYCwHDIY04EiS6Sp6jSlgmX8yYAIwxncfkBZsIhJaSi6ZlSCU5WMyX5S8sW6u6RW5aAADUoBpb5+mGdeLwktFqYvFmfgIfwPSeVC-mGUFvaheFkXsKsQ3XtluXerGTGWnK02tdIJKhitbVRt62TYQUkjtbWuYFlCEFAdua5gdWtbovWC41AAku5SRgvsew6KA52seuaxcKs-RgthBHIYcLAOapySFJp2k9Que2eIdoAANpnVB4nulNAWrSSAC6qRUTRaHYvqoDJBwGwNpeYDICp3ZmOTqz8OT4MdlSyJ7GpUMbDDhZHPTMxzKA146Pk+gHJ48wcH1nbuhw6I+U28MHdZSibWt-jE1UNTQAFowEs+Jnfr+HBTccJpi9c8j854PY6XsZm2fYDD5oWSs0two0cAA6shfi0Rit2U6z+2I27-i9f1-lQil7JSTJoBPeDr29hsVx6dIAg9JYRvDvsbAszDqxggeGwqfZbAsNMDBh38Sg1z1xf0tCqJoqy55VAt-FLfXob1zxVRNkAA) script that mimics the Action's work. 

I use to test certain files paths to see what the outcome would look like without having to make a commit to GitHub, run the Action and wait for every tiny change

Put your string paths in these called out variables, run it and check out Logs pane

![image](https://user-images.githubusercontent.com/3520532/93099172-ba92a280-f675-11ea-8f95-32fc37d66eb4.png)

**Comment by jacwil** [comment]
I'm also running into this issue. I suspect leading and trailing slashes in `sourceFolder` and `localFilePath` has an effect on the resulting `trimmedPath`. I tested in the TypeScript Playground (very useful!) and will submit a PR for review.

**Comment by LanceMcCarthy** [comment]
Thank you, I will review it today and push out a new release.

**Comment by LanceMcCarthy** [comment]
I have validated, built, test and released v1.8.3 to GitHub Actions Marketplace

- @jacwil Thank you for opening the PR, 
- @andrewconnell Can you please let me know if you're seeing any problems after updating the workflow to use v1.8.3

If you'd like to see the specifics:

- Here is the GH Action build results (it also contains Test results) https://github.com/LanceMcCarthy/Action-AzureBlobUpload/actions/workflows/main_release.yml
- Here's the release page  https://github.com/LanceMcCarthy/Action-AzureBlobUpload/releases/tag/v1.8.3

**Comment by andrewconnell** [comment]
@LanceMcCarthy I chose to implement the upload using a different method back then. Bit swamped and the workflow works now so no offense if I don't get a chance to go back and test it out ¯\_(ツ)_/¯

**Comment by LanceMcCarthy** [comment]
@andrewconnell no offense taken! If you start a new project and need this again, I'm happy to help.
