### ISSUE TITLE
Multiple File Upload to Blob Storage

### ISSUE THREAD

**Issue by marvenp** [LanceMcCarthy/Action-AzureBlobUpload#443]
I am not sure about the pattern but I am using the GitHub action to pull JSON files from my GitHub folder and upload it to Blob Storage for configuration setup purposes. 

There are a total of 21 JSON configuration files. But somehow, when I run the workflow, some of the files are getting missed.

Also, it's not a filename issue since every time some different file ends up missing.

I am using this action.

   - name: Uploading to Azure storage...
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          container_name: ${{ vars.AZURE_DTS_METADATA_CONTAINER }}
          source_folder: ${{ vars.DTS_SRC_FOLDER }}
          destination_folder: ${{ steps.setup_dest.outputs.destination }}

Also in logs, it shows all files being uploaded but in blob storage, some are missing.

**Comment by LanceMcCarthy** [comment]
Hi, it looks like you're using an older version. Can you please try `v3` and see if that resolves it?

`uses: LanceMcCarthy/Action-AzureBlobUpload@v3`
